name: "Combine Dependabot Pull Requests"

on:
  # schedule:
  #   - cron: '1/5 * * * *'

  workflow_dispatch:

jobs:
  combine-prs:
    name: "Combine Pull Requests"
    runs-on: ubuntu-20.04
    steps:
      - uses: hmcts/am-github-actions/combine-prs@master
        with:
          branchPrefix: "dependabot"
          mustBeGreen: "true"
          combineBranchName: "combine-prs-branch"
          ignoreLabel: "nocombine"
          closeCombinedPrs: "true"
          githubToken: "${{ secrets.GITHUB_TOKEN }}"